title: "한단비내린 – 음악+AI 연구자"
description: "AI와 음악의 접점을 연구하는 개인 포트폴리오"
url: "https://danbinaerinHan.github.io"
baseurl: "/danbinaerinhan"

remote_theme: ItsPatrq/minimal-music-project

plugins:
  - jekyll-feed

collections:
  discography:
    output: true
  collaborations:
    output: true

# 메뉴 구성
menu_pages:
  - title: "홈"
    url: "/"
  - title: "음악"
    url: "/discography/"
  - title: "협업"
    url: "/collaborations/"
  - title: "블로그"
    url: "/blog/"

# 소셜 링크 등
social_links:
  - name: "GitHub"
    url: "https://github.com/danbinaerinHan"
    icon: "fab fa-github"
  - name: "ResearchGate"
    url: "https://www.researchgate.net"
    icon: "fab fa-researchgate"
